CREATE TABLE [dbo].[Country] (
    [Country]   NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Country] ASC)
);

INSERT INTO COUNTRY VALUES('Egypt');

INSERT INTO COUNTRY VALUES('England');

INSERT INTO COUNTRY VALUES('South Africa');

INSERT INTO COUNTRY VALUES('Morroco');

INSERT INTO COUNTRY VALUES('Portugal');

INSERT INTO COUNTRY VALUES('Brazil');

INSERT INTO COUNTRY VALUES('France');

INSERT INTO COUNTRY VALUES('Italy');

INSERT INTO COUNTRY VALUES('United states');

INSERT INTO COUNTRY VALUES('Palestine');
